package com\example\employee.controller;

import com\example\employee.model.Create;
import com\example\employee.service.CreateService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Create REST Controller - Auto-generated by GitHub Agent
 * Following Spring Boot patterns found in existing controllers
 */
@RestController
@RequestMapping("/api/create")
@CrossOrigin(origins = "*")
public class CreateController {
    
    @Autowired
    private CreateService createService;
    
    @GetMapping
    public ResponseEntity<List<Create>> getAll() {
        List<Create> items = createService.findAll();
        return ResponseEntity.ok(items);
    }
    
    @GetMapping("/{id}")
    public ResponseEntity<Create> getById(@PathVariable Long id) {
        Create item = createService.findById(id);
        if (item != null) {
            return ResponseEntity.ok(item);
        }
        return ResponseEntity.notFound().build();
    }
    
    @PostMapping
    public ResponseEntity<Create> create(@RequestBody Create create) {
        Create saved = createService.save(create);
        return ResponseEntity.ok(saved);
    }
    
    @PutMapping("/{id}")
    public ResponseEntity<Create> update(@PathVariable Long id, @RequestBody Create create) {
        Create updated = createService.update(id, create);
        if (updated != null) {
            return ResponseEntity.ok(updated);
        }
        return ResponseEntity.notFound().build();
    }
    
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        createService.delete(id);
        return ResponseEntity.ok().build();
    }
}
