package com\example\employee.controller;

import com\example\employee.model.Endpoint;
import com\example\employee.service.EndpointService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * Endpoint REST Controller - Auto-generated by GitHub Agent
 * Following Spring Boot patterns found in existing controllers
 */
@RestController
@RequestMapping("/api/endpoint")
@CrossOrigin(origins = "*")
public class EndpointController {
    
    @Autowired
    private EndpointService endpointService;
    
    @GetMapping
    public ResponseEntity<List<Endpoint>> getAll() {
        List<Endpoint> items = endpointService.findAll();
        return ResponseEntity.ok(items);
    }
    
    @GetMapping("/{id}")
    public ResponseEntity<Endpoint> getById(@PathVariable Long id) {
        Endpoint item = endpointService.findById(id);
        if (item != null) {
            return ResponseEntity.ok(item);
        }
        return ResponseEntity.notFound().build();
    }
    
    @PostMapping
    public ResponseEntity<Endpoint> create(@RequestBody Endpoint endpoint) {
        Endpoint saved = endpointService.save(endpoint);
        return ResponseEntity.ok(saved);
    }
    
    @PutMapping("/{id}")
    public ResponseEntity<Endpoint> update(@PathVariable Long id, @RequestBody Endpoint endpoint) {
        Endpoint updated = endpointService.update(id, endpoint);
        if (updated != null) {
            return ResponseEntity.ok(updated);
        }
        return ResponseEntity.notFound().build();
    }
    
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> delete(@PathVariable Long id) {
        endpointService.delete(id);
        return ResponseEntity.ok().build();
    }
}
