package com\example\employee.repository;

import com\example\employee.model.Category;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Category Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface CategoryRepository extends JpaRepository<Category, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Category findByName(String name);
    
    // Example: Find by description containing
    // List<Category> findByDescriptionContaining(String keyword);
}
