package com\example\employee.repository;

import com\example\employee.model.Create;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Create Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface CreateRepository extends JpaRepository<Create, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Create findByName(String name);
    
    // Example: Find by description containing
    // List<Create> findByDescriptionContaining(String keyword);
}
