package com\example\employee.repository;

import com\example\employee.model.Endpoint;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Endpoint Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface EndpointRepository extends JpaRepository<Endpoint, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Endpoint findByName(String name);
    
    // Example: Find by description containing
    // List<Endpoint> findByDescriptionContaining(String keyword);
}
