package com\example\employee.repository;

import com\example\employee.model.End;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * End Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface EndRepository extends JpaRepository<End, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // End findByName(String name);
    
    // Example: Find by description containing
    // List<End> findByDescriptionContaining(String keyword);
}
