package com\example\employee.repository;

import com\example\employee.model.Entity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Entity Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface EntityRepository extends JpaRepository<Entity, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Entity findByName(String name);
    
    // Example: Find by description containing
    // List<Entity> findByDescriptionContaining(String keyword);
}
