package com\example\employee.repository;

import com\example\employee.model.Feature;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Feature Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface FeatureRepository extends JpaRepository<Feature, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Feature findByName(String name);
    
    // Example: Find by description containing
    // List<Feature> findByDescriptionContaining(String keyword);
}
