package com\example\employee.repository;

import com\example\employee.model.Flow;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Flow Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface FlowRepository extends JpaRepository<Flow, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Flow findByName(String name);
    
    // Example: Find by description containing
    // List<Flow> findByDescriptionContaining(String keyword);
}
