package com\example\employee.repository;

import com\example\employee.model.Order;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Order Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface OrderRepository extends JpaRepository<Order, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Order findByName(String name);
    
    // Example: Find by description containing
    // List<Order> findByDescriptionContaining(String keyword);
}
