package com\example\employee.repository;

import com\example\employee.model.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Product Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface ProductRepository extends JpaRepository<Product, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Product findByName(String name);
    
    // Example: Find by description containing
    // List<Product> findByDescriptionContaining(String keyword);
}
