package com\example\employee.repository;

import com\example\employee.model.Vechile;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Vechile Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface VechileRepository extends JpaRepository<Vechile, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Vechile findByName(String name);
    
    // Example: Find by description containing
    // List<Vechile> findByDescriptionContaining(String keyword);
}
