package com\example\employee.repository;

import com\example\employee.model.Vehicle;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Vehicle Repository - Auto-generated by GitHub Agent
 * Following repository patterns found in existing code
 */
@Repository
public interface VehicleRepository extends JpaRepository<Vehicle, Long> {
    
    // JpaRepository provides basic CRUD operations
    // Add custom query methods here if needed
    
    // Example: Find by name
    // Vehicle findByName(String name);
    
    // Example: Find by description containing
    // List<Vehicle> findByDescriptionContaining(String keyword);
}
