package com\example\employee.service;

import com\example\employee.model.Create;
import com\example\employee.repository.CreateRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

/**
 * Create Service - Auto-generated by GitHub Agent
 * Following service patterns found in existing code
 */
@Service
public class CreateService {
    
    @Autowired
    private CreateRepository createRepository;
    
    public List<Create> findAll() {
        return createRepository.findAll();
    }
    
    public Create findById(Long id) {
        Optional<Create> optional = createRepository.findById(id);
        return optional.orElse(null);
    }
    
    public Create save(Create create) {
        return createRepository.save(create);
    }
    
    public Create update(Long id, Create create) {
        if (createRepository.existsById(id)) {
            create.setId(id);
            return createRepository.save(create);
        }
        return null;
    }
    
    public void delete(Long id) {
        createRepository.deleteById(id);
    }
}
