package com\example\employee.service;

import com\example\employee.model.Endpoint;
import com\example\employee.repository.EndpointRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

/**
 * Endpoint Service - Auto-generated by GitHub Agent
 * Following service patterns found in existing code
 */
@Service
public class EndpointService {
    
    @Autowired
    private EndpointRepository endpointRepository;
    
    public List<Endpoint> findAll() {
        return endpointRepository.findAll();
    }
    
    public Endpoint findById(Long id) {
        Optional<Endpoint> optional = endpointRepository.findById(id);
        return optional.orElse(null);
    }
    
    public Endpoint save(Endpoint endpoint) {
        return endpointRepository.save(endpoint);
    }
    
    public Endpoint update(Long id, Endpoint endpoint) {
        if (endpointRepository.existsById(id)) {
            endpoint.setId(id);
            return endpointRepository.save(endpoint);
        }
        return null;
    }
    
    public void delete(Long id) {
        endpointRepository.deleteById(id);
    }
}
