package com\example\employee.service;

import com\example\employee.model.Missing;
import com\example\employee.repository.MissingRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

/**
 * Missing Service - Auto-generated by GitHub Agent
 * Following service patterns found in existing code
 */
@Service
public class MissingService {
    
    @Autowired
    private MissingRepository missingRepository;
    
    public List<Missing> findAll() {
        return missingRepository.findAll();
    }
    
    public Missing findById(Long id) {
        Optional<Missing> optional = missingRepository.findById(id);
        return optional.orElse(null);
    }
    
    public Missing save(Missing missing) {
        return missingRepository.save(missing);
    }
    
    public Missing update(Long id, Missing missing) {
        if (missingRepository.existsById(id)) {
            missing.setId(id);
            return missingRepository.save(missing);
        }
        return null;
    }
    
    public void delete(Long id) {
        missingRepository.deleteById(id);
    }
}
