package com\example\employee.service;

import com\example\employee.model.Vehicle;
import com\example\employee.repository.VehicleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Optional;

/**
 * Vehicle Service - Auto-generated by GitHub Agent
 * Following service patterns found in existing code
 */
@Service
public class VehicleService {
    
    @Autowired
    private VehicleRepository vehicleRepository;
    
    public List<Vehicle> findAll() {
        return vehicleRepository.findAll();
    }
    
    public Vehicle findById(Long id) {
        Optional<Vehicle> optional = vehicleRepository.findById(id);
        return optional.orElse(null);
    }
    
    public Vehicle save(Vehicle vehicle) {
        return vehicleRepository.save(vehicle);
    }
    
    public Vehicle update(Long id, Vehicle vehicle) {
        if (vehicleRepository.existsById(id)) {
            vehicle.setId(id);
            return vehicleRepository.save(vehicle);
        }
        return null;
    }
    
    public void delete(Long id) {
        vehicleRepository.deleteById(id);
    }
}
